set allow-duplicate-recipes := false
set ignore-comments := true

_default:
	#!/usr/bin/env bash
	/usr/bin/just --list --list-heading $'Available commands:\n' --list-prefix $' - '

reboot-to-bios:
	#!/usr/bin/env bash
	if [ -d /sys/firmware/efi ]; then
		systemctl reboot --firmware-setup
	else
		echo "Rebooting to legacy BIOS from OS is not supported."
	fi

logs-this-boot:
	sudo journalctl --no-hostname -b 0

logs-last-boot:
	sudo journalctl --no-hostname -b -1


system-update:
	#!/usr/bin/env fish
	flatpak update --assumeyes --noninteractive
	mise upgrade
	if type -q fisher
		fisher update
	end
	sudo bootc update

system-clean:
	#!/usr/bin/env bash
	podman image prune -af
	podman volume prune -f
	docker image prune -af
	docker volume prune -f
	flatpak uninstall --unused --noninteractive --assumeyes
	# rpm-ostree cleanup -bm

[no-exit-message]
firmware-update:
	fwupdmgr refresh --force
	fwupdmgr update

changelogs:
	rpm-ostree db diff --changelogs

bios-info:
	#!/usr/bin/env bash
	echo "Manufacturer: $(sudo dmidecode -s baseboard-manufacturer)"
	echo "Product Name: $(sudo dmidecode -s baseboard-product-name)"
	echo "Version: $(sudo dmidecode -s bios-version)"
	echo "Release Date: $(sudo dmidecode -s bios-release-date)"

setup-groups:
	#!/usr/bin/env bash
	sudo groupadd -f docker
	sudo groupadd --system -f libvirt
	sudo usermod -a -G docker "$(whoami)"
	sudo usermod -a -G libvirt "$(whoami)"

create-firewall-zone-for-vnet:
	#!/usr/bin/env bash
	sudo firewall-cmd --permanent --new-zone=libvirt-vnet
	sudo firewall-cmd --permanent --zone=libvirt-vnet --set-target=ACCEPT
	sudo firewall-cmd --permanent --zone=libvirt-vnet --add-interface="vnet+"

install-recommended-misetools:
	#!/usr/bin/env bash
	function implement() {
		mise install "${1}"@latest
		mise use -g "${1}"@latest
	}

	implement calicoctl
	implement go
	implement helm
	implement kubectl
	implement kubectx
	implement kubens
	implement kubie
	implement kustomize
	implement opentofu
	implement talosctl
	implement trivy
	implement velero

show-toolbox-examples:
	#!/usr/bin/env bash
	echo "Example for Images:"
	echo "toolbox create -c rhel-8 -i registry.access.redhat.com/ubi8/toolbox:latest"
	echo "toolbox create -c rhel-9 -i registry.access.redhat.com/ubi9/toolbox:latest"
	echo "toolbox create -c rhel-10 -i registry.access.redhat.com/ubi10/toolbox:latest"
	echo "toolbox create -c fedora-41 -i registry.fedoraproject.org/fedora-toolbox:41"

show-distrobox-examples:
	#!/usr/bin/env bash
	echo "Example for Images:"
	echo "distrobox create -n alma -i quay.io/toolbx-images/almalinux-toolbox:latest"
	echo "distrobox create -n arch -i ghcr.io/ublue-os/arch-toolbox:latest"
	echo "distrobox create -n centos -i quay.io/toolbx-images/centos-toolbox:latest"
	echo "distrobox create -n debian -i quay.io/toolbx-images/debian-toolbox:unstable"
	echo "distrobox create -n fedora -i ghcr.io/ublue-os/fedora-toolbox:latest"
	echo "distrobox create -n opensuse -i quay.io/toolbx-images/opensuse-toolbox:tumbleweed"
	echo "distrobox create -n ubuntu -i ghcr.io/ublue-os/ubuntu-toolbox:latest"
