# Generated by go2rpm 1.15.0
%bcond check 1
%bcond bootstrap 0

%global debug_package %{nil}

%if %{with bootstrap}
%global __requires_exclude %{?__requires_exclude:%{__requires_exclude}|}^golang\\(.*\\)$
%endif

# https://github.com/twpayne/chezmoi
%global goipath         github.com/twpayne/chezmoi
Version:                2.63.1
%gometa -f

%global common_description %{expand:
Manage your dotfiles across multiple diverse machines, securely.}

%global golicenses      LICENSE
%global godocs          README.md

Name:           chezmoi
Release:        %autorelease
Summary:        Manage your dotfiles across multiple diverse machines, securely

License:        MIT
URL:            %{gourl}
Source:         %{gosource}

BuildRequires: git
%if 0%{?fedora}
BuildRequires: go-rpm-macros
%endif
BuildRequires: golang >= 1.24.5

%description %{common_description}

%gopkg

%prep
%goprep -A -k
%autopatch -p1

%if %{without bootstrap}
%generate_buildrequires
%endif

%if %{without bootstrap}
%build
DATE=$( date -u '+%Y-%m-%dT%H:%M:%SZ' )
go build -ldflags "-X main.version=%{version} \
                   -X main.date=$DATE \
                   -X \"main.builtBy=Fedora COPR"\" .
%endif

%install
%gopkginstall
%if %{without bootstrap}
install -m 0755 -vd         %{buildroot}%{_bindir}
install -m 0755 -vp chezmoi %{buildroot}%{_bindir}/

install -Dpm 0644 completions/%{name}-completion.bash %{buildroot}%{bash_completions_dir}/%{name}.bash
install -Dpm 0644 completions/%{name}.fish            -t %{buildroot}%{fish_completions_dir}
install -Dpm 0644 completions/%{name}.zsh             %{buildroot}%{zsh_completions_dir}/_%{name}
%endif

%if %{without bootstrap}
%if %{with check}
%check
make test
%endif
%endif

%if %{without bootstrap}
%files
%license %{golicenses}
%doc %{godocs}
%{_bindir}/chezmoi
%{bash_completions_dir}/%{name}.bash
%{fish_completions_dir}/%{name}.fish
%{zsh_completions_dir}/_%{name}
%endif

%gopkgfiles
%changelog
%autochangelog
