---
# yamllint disable rule:line-length
name: backgrounds-aurora copr rebuild
on:
  push:
    branches:
      - main
    paths:
      - image-branding/backgrounds-aurora/backgrounds-aurora.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Run webhook for copr
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/197881/b132ac2b-dd7b-41ca-99e1-bb25d45b8729/backgrounds-aurora
