---
# yamllint disable rule:line-length
name: blisp copr rebuild
on:
  push:
    branches:
      - main
    paths:
      - tools-misc/blisp/blisp.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Run webhook for copr
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/197880/c61ad174-3b66-4910-b4fb-8d33b0b9abdb/blisp
