---
# yamllint disable rule:line-length
name: eza copr rebuild
on:
  push:
    branches:
      - main
    paths:
      - tools-rust/eza/eza.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Run webhook for copr
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/197879/8b58d803-7237-4892-9ddd-3fc56b27df3a/eza
