---
# yamllint disable rule:line-length
name: oha copr rebuild
on:
  push:
    branches:
      - main
    paths:
      - oha/oha.spec
  workflow_dispatch:

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Run webhook for copr
        run: |
          curl -X POST https://copr.fedorainfracloud.org/webhooks/custom/183973/b217f930-6409-41d8-ad9c-eefe9a425524/oha/
